name: test-on-push
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04  
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          pip install coverage pytest
      - name: flake8 run
        run: |
          make lint
      - name: pytest run
        run: |
          make test
      - name: Test & publish code coverage
        env:
          CC_TEST_REPORTER_ID: 8e1ed92de590fc77c73fe71948474a373195fd7c0ad7e48d30a14db22a55851b
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          coverage run --source=. -m pytest
          ./cc-test-reporter after-build
