name: test-on-push
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04  
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: flake8 run
        run: |
          make lint
      - name: Test & publish code coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.MY_CC_TESTREP_ID }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          poetry run coverage run --source=. -m pytest
          poetry run coverage xml
          ./cc-test-reporter format-coverage coverage.xml --input-type coverage.py
          ./cc-test-reporter upload-coverage
